set nocompatible
filetype off

" Bundle init from github.com/hinrik/dotfiles
" Download vundle
if !isdirectory(expand("~/.vim/bundle/vundle"))
    !mkdir -p ~/.vim/bundle
    !git clone git://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
    let s:bootstrap=1
endif

" Load bundles with vundle
set runtimepath+=~/.vim/bundle/vundle/
call vundle#rc()
Bundle 'gmarik/vundle'

Bundle 'git://github.com/kien/ctrlp.vim.git'
Bundle 'git://github.com/tpope/vim-fugitive.git'
Bundle 'git://github.com/tpope/vim-markdown.git'
Bundle 'git://github.com/lepture/vim-jinja.git'
Bundle 'git://github.com/pthrasher/conqueterm-vim.git'
Bundle 'git://github.com/pangloss/vim-javascript.git'
Bundle 'git://github.com/scrooloose/nerdcommenter.git'
Bundle 'git://github.com/vim-pandoc/vim-pandoc.git'
Bundle 'git://github.com/godlygeek/tabular.git'
Bundle 'git://github.com/dhruvasagar/vim-table-mode.git'
Bundle 'git://github.com/hynek/vim-python-pep8-indent.git'
Bundle 'git://github.com/scrooloose/syntastic.git'
Bundle 'git://github.com/jnwhiteh/vim-golang.git'


" Bootstrap vundle
if exists("s:bootstrap") && s:bootstrap
    unlet s:bootstrap
    BundleInstall
endif

syntax on
filetype plugin indent on

" Indenting
set tabstop=2
set shiftwidth=2
set autoindent
set expandtab
set smarttab

set cursorline
set visualbell
set title
set titleold="Terminal"
set number
set showcmd

set wrap
set textwidth=78

" from http://github.com/mitsuhiko/dotfiles/blob/master/vim/vimrc
" sets leader to ','
let mapleader=","

" customize the wildmenu
set wildmenu
set wildignore=*.o,*.pyc,*.bak,*.jpg,*.jpeg,*.png,*.giv
set wildmode=list:full

" hide matches on <leader>space
nnoremap <leader><space> :nohlsearch<cr>

" Set working directory
nnoremap <leader>. :lcd %:p:h<CR>

" Toggle paste mode and line numbering, show current state
nnoremap <leader>p :setlocal paste! paste?<cr>
nnoremap <leader>n :setlocal number! number?<cr>

" Make the command line two lines high and change the statusline display to
" something that looks useful.
set cmdheight=2
set laststatus=2
set showcmd

" keep more lines for scope
set scrolloff=4

" better search
set hlsearch
set incsearch

" force me to use home row movement keys
nnoremap <up> <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
inoremap <up> <nop>
inoremap <down> <nop>
inoremap <left> <nop>
inoremap <right> <nop>
nnoremap j gj
nnoremap k gk

" disable f1
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

" disable weird "Ex mode"
noremap Q <ESC>

" split window movement
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" disable annoying 'Ex' mode
noremap Q <Nop>

" make :W = :w
cnoreabbrev W w

" shortcuts for using console
nnoremap <leader>b :ConqueTerm bash<cr>

" shortcut for code folding
nnoremap <space> za
vnoremap <space> zf

" Highlight trailing whitespace
" From http://vim.wikia.com/wiki/Highlight_unwanted_spaces example: 
highlight ExtraWhitespace ctermbg=darkgreen guibg=darkgreen
augroup WhitespaceMatch
  " Remove ALL autocommands for the WhitespaceMatch group.
  autocmd!
  autocmd BufWinEnter * let w:whitespace_match_number = matchadd('ExtraWhitespace', '\s\+$')
  autocmd InsertEnter * call s:ToggleWhitespaceMatch('i')
  autocmd InsertLeave * call s:ToggleWhitespaceMatch('n')
augroup END
function! s:ToggleWhitespaceMatch(mode)
  let pattern = (a:mode == 'i') ? '\s\+\%#\@<!$' : '\s\+$'
  if exists('w:whitespace_match_number')
    call matchdelete(w:whitespace_match_number)
    call matchadd('ExtraWhitespace', pattern, 10, w:whitespace_match_number)
  else
    " Something went wrong, try to be graceful.
    let w:whitespace_match_number =  matchadd('ExtraWhitespace', pattern)
  endif
endfunction

" Highlight non-ascii characters (i.e., outside the range from ' ' (space)
" to tilde) ☃✈‽‘’☣
highlight NonASCII ctermfg=gray ctermbg=darkblue
autocmd BufWinEnter * call matchadd('NonASCII', '[^\ -~]')

" Remove trailing whitespace on save (for source files)
" from http://stackoverflow.com/q/356126
fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd FileType c,cpp,css,erb,html,java,javascript,php,python,rst,ruby,tex,text autocmd BufWritePre <buffer> :call <SID>StripTrailingWhitespaces()

" Pandoc settings
let g:pandoc_no_folding = 1
let g:pandoc_no_spans = 1
let g:pandoc_use_hard_wraps = 1

au BufNewFile,BufRead *.wsgi setf python
au FileType css setlocal tabstop=4
au FileType java setlocal tabstop=8
au FileType vim setlocal expandtab shiftwidth=2 tabstop=8 softtabstop=2
au FileType tex setlocal textwidth=80
au FileType python setlocal tabstop=4 shiftwidth=4 foldmethod=indent foldnestmax=2
